version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - BUILDKITE
      - BUILDKITE_COMMIT
      - BUILDKITE_BRANCH
      - BUILDKITE_PULL_REQUEST
      - BUILDKITE_BUILD_ID
      - PERCY_TOKEN
      - PERCY_PROJECT
      - PERCY_API
